# Generated by Django 4.1.3 on 2022-11-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20221101_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('usia', models.IntegerField()),
                ('lama', models.IntegerField()),
                ('link_foto', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
